diseases = [
    "Hypertension", "Diabetes", "Heart disease", "Cancer", "Stroke", "Arthritis", "Alzheimer's disease",
    "Asthma", "COPD (Chronic Obstructive Pulmonary Disease)", "Influenza", "Pneumonia", "Depression", "Anxiety disorders",
    "Osteoporosis", "Obesity", "HIV/AIDS", "Hepatitis", "Malaria", "Tuberculosis", "Cholera", "Measles", "Chickenpox",
    "Dengue fever", "Zika virus", "Ebola", "Chlamydia", "Gonorrhea", "Syphilis", "Herpes", "Inflammatory bowel disease (IBD)",
    "Crohn's disease", "Ulcerative colitis", "Rheumatoid arthritis", "Multiple sclerosis", "Parkinson's disease",
    "Migraine", "Chronic kidney disease", "Cirrhosis", "Irritable bowel syndrome (IBS)", "Psoriasis", "Eczema", "Lupus",
    "Fibromyalgia", "PCOS (Polycystic ovary syndrome)", "Endometriosis", "Menopause", "Erectile dysfunction",
    "Premature ejaculation", "Infertility", "Allergies", "Celiac disease", "Glaucoma", "Macular degeneration",
    "Osteoarthritis", "Gout", "Anemia", "Leukemia", "Lymphoma", "Pancreatitis", "Gastritis",
    "GERD (Gastroesophageal Reflux Disease)", "Peptic ulcer", "Autism", "ADHD (Attention-Deficit/Hyperactivity Disorder)",
    "Schizophrenia", "Bipolar disorder", "OCD (Obsessive-Compulsive Disorder)", "PTSD (Post-Traumatic Stress Disorder)",
    "Anorexia nervosa", "Bulimia nervosa", "Binge-eating disorder", "Sickle cell anemia", "Hemophilia"
]
symptoms_list = [
    "High blood pressure", "Headaches", "Dizziness", "Increased thirst", "Frequent urination", "Fatigue", "Chest pain",
    "Shortness of breath", "Lumps", "Weight loss", "Numbness", "Confusion", "Severe headache", "Trouble walking", "Joint pain",
    "Stiffness", "Swelling", "Memory loss", "Disorientation", "Behavior changes", "Wheezing", "Coughing", "Chronic cough",
    "Fever", "Sore throat", "High fever", "Cough with mucus", "Jaundice", "Abdominal pain", "Dark urine", "Vomiting",
    "Dehydration", "Itchy rash", "Sweating", "Dry skin", "Inflammation", "Hot flashes", "Night sweats", "Mood swings",
    "Difficulty achieving/maintaining an erection", "Premature ejaculation", "Difficulty conceiving", "Sneezing",
    "Runny/stuffy nose", "Itchy/watery eyes", "Skin rash", "Digestive problems", "Diarrhea", "Increased intraocular pressure",
    "Gradual loss of peripheral vision", "Blurred/distorted central vision", "Reduced range of motion", "Sudden, severe joint pain",
    "Swelling", "Redness", "Weakness", "Pale skin", "Shortness of breath", "Frequent infections", "Enlarged lymph nodes",
    "Swollen lymph nodes", "Unexplained weight loss", "Severe abdominal pain", "Nausea", "Regurgitation of stomach acid",
    "Burning or gnawing pain in the stomach", "Delusions", "Hallucinations", "Disorganized thinking", "Social withdrawal",
    "Episodes of mania and depression", "Mood swings", "Obsessions", "Compulsions", "Flashbacks", "Nightmares", "Anxiety",
    "Avoidance behaviors", "Extreme weight loss", "Fear of gaining weight", "Distorted body image", "Binge eating", "Purging behaviors",
    "Guilt and shame", "Recurrent episodes of overeating", "Loss of control", "Pain crises", "Jaundice", "Swelling of hands/feet",
    "Excessive bleeding", "Easy bruising", "Joint pain/swelling"
]
disease_information = [
    "Hypertension is a common medical condition where the force of blood against the walls of your arteries is consistently too high. It can lead to serious health problems, such as heart disease and stroke.",
    "Diabetes is a chronic condition that affects how your body processes glucose (sugar). There are different types of diabetes, including Type 1 and Type 2, both of which require careful management.",
    "Heart disease refers to a range of conditions that affect your heart, including coronary artery disease, heart failure, and arrhythmias. It's a leading cause of death in many countries.",
    "Cancer is a group of diseases characterized by the uncontrolled growth and spread of abnormal cells. It can affect virtually any part of the body and may have different treatment approaches.",
    "Stroke is a medical emergency that occurs when there's a disruption in the blood supply to the brain. Immediate medical attention is crucial to minimize damage.",
    "Arthritis is a common condition that causes joint pain, stiffness, and swelling. There are many types of arthritis, including osteoarthritis and rheumatoid arthritis.",
    "Alzheimer's disease is a progressive brain disorder that affects memory, thinking, and behavior. It's the most common cause of dementia in older adults.",
    "Asthma is a chronic respiratory condition that causes the airways to become inflamed and narrowed, leading to difficulty in breathing. It can often be managed with medication and lifestyle changes.",
    "COPD (Chronic Obstructive Pulmonary Disease) is a group of lung diseases that includes chronic bronchitis and emphysema. It's characterized by difficulty breathing and decreased lung function.",
    "Influenza, or the flu, is a contagious respiratory illness caused by influenza viruses. Vaccination is recommended to prevent severe cases.",
    "Pneumonia is an infection that inflames the air sacs in the lungs and can cause symptoms like cough, fever, and difficulty breathing. Treatment typically involves antibiotics.",
    "Depression is a mood disorder that leads to persistent feelings of sadness and loss of interest in daily activities. It can be managed with therapy, medication, or a combination of both.",
    "Anxiety disorders encompass a range of conditions, including generalized anxiety disorder, panic disorder, and social anxiety. Treatment options include therapy and medication.",
    "Osteoporosis is a bone disease that makes bones weak and more likely to break. It's particularly common in postmenopausal women.",
    "Obesity is a condition characterized by excess body fat. It can increase the risk of various health problems, including heart disease and diabetes.",
    "HIV/AIDS is a viral infection that attacks the immune system. Antiretroviral therapy can help manage the virus and slow the progression of the disease.",
    "Hepatitis refers to inflammation of the liver, often caused by viral infections. Different types of hepatitis have varying treatment approaches.",
    "Malaria is a mosquito-borne disease caused by parasites. Prevention through the use of bed nets and anti-malarial drugs is essential.",
    "Tuberculosis (TB) is a bacterial infection that primarily affects the lungs. It's treated with a combination of antibiotics.",
    "Cholera is a bacterial infection that leads to severe diarrhea and dehydration. Rehydration therapy is crucial in managing cholera.",
    "Measles is a highly contagious viral infection that causes a characteristic red rash. Vaccination is key to preventing measles outbreaks.",
    "Chickenpox is a viral infection that causes an itchy rash and fever. Vaccination is effective in preventing chickenpox.",
    "Dengue fever is a mosquito-borne viral illness that can lead to severe flu-like symptoms. There is no specific treatment, and management focuses on symptom relief.",
    "Zika virus is transmitted primarily through mosquito bites. Pregnant women should take precautions, as Zika can cause birth defects.",
    "Ebola is a rare but severe viral disease. Treatment involves supportive care and isolation to prevent its spread.",
    "Chlamydia is a common sexually transmitted infection (STI) caused by bacteria. It can be treated with antibiotics.",
    "Gonorrhea is another common STI caused by bacteria. Antibiotics are used to treat gonorrhea.",
    "Syphilis is a bacterial STI that occurs in stages. It's treated with antibiotics.",
    "Herpes is a viral STI that can cause oral or genital sores. Antiviral medications can help manage symptoms.",
    "Inflammatory bowel disease (IBD) is a group of disorders that includes Crohn's disease and ulcerative colitis. Treatment may involve medication and sometimes surgery.",
    "Crohn's disease is a type of IBD that can cause inflammation and damage throughout the digestive tract. Treatment may include medication and dietary changes.",
    "Ulcerative colitis is another type of IBD that primarily affects the colon and rectum. Treatment aims to reduce inflammation and manage symptoms.",
    "Rheumatoid arthritis is an autoimmune disorder that affects the joints. Medications and physical therapy can help manage the condition.",
    "Multiple sclerosis is a neurological condition that affects the central nervous system. Treatment focuses on managing symptoms and slowing the progression of the disease.",
    "Parkinson's disease is a neurodegenerative disorder that affects movement and coordination. Medications and therapy can help manage symptoms.",
    "Migraine is a type of headache that can cause severe throbbing pain, often accompanied by other symptoms. Treatment includes medication and lifestyle changes.",
    "Chronic kidney disease is a long-term condition that impairs kidney function. Treatment may involve medication and lifestyle adjustments.",
    "Cirrhosis is a late stage of scarring (fibrosis) of the liver. Lifestyle changes and medical treatment can help manage the condition.",
    "Irritable bowel syndrome (IBS) is a gastrointestinal disorder that can cause abdominal pain and changes in bowel habits. Management includes dietary changes and medication.",
    "Psoriasis is a chronic skin condition that causes cells to build up rapidly on the surface of the skin. Treatments include topical creams, light therapy, and medications.",
    "Eczema, or atopic dermatitis, is a skin condition that leads to itchy and inflamed skin. Treatment includes emollients and topical steroids.",
    "Lupus is an autoimmune disease that can affect various body systems. Treatment depends on the specific symptoms and can include medication and lifestyle changes.",
    "Fibromyalgia is a chronic condition characterized by widespread musculoskeletal pain. Management may include medication and lifestyle strategies.",
    "PCOS (Polycystic ovary syndrome) is a hormonal disorder that can lead to irregular periods and difficulty getting pregnant. Management includes lifestyle changes and medication.",
    "Endometriosis is a condition in which tissue similar to the lining of the uterus grows outside the uterus. Treatment may involve medication and surgery.",
    "Menopause is a natural biological process that marks the end of a woman's reproductive years. Management may include hormone therapy and lifestyle changes.",
    "Erectile dysfunction is the inability to get and keep an erection firm enough for sex. Treatment may involve medication, therapy, or other approaches.",
    "Premature ejaculation is a common sexual problem that can be treated with counseling and, in some cases, medication.",
    "Infertility is the inability to conceive after a year of unprotected sex. Treatment depends on the underlying causes and may include medications, surgery, or assisted reproductive technologies.",
    "Allergies occur when the immune system reacts to a foreign substance (allergen). Treatment often involves allergen avoidance and medication.",
    "Celiac disease is an autoimmune disorder in which eating gluten leads to damage in the small intestine. The primary treatment is a gluten-free diet.",
    "Glaucoma is a group of eye conditions that damage the optic nerve. Treatment includes eye drops, medication, or surgery.",
    "Macular degeneration is a chronic eye disease that affects the macula, leading to vision loss. Treatment varies based on the type of macular degeneration.",
    "Osteoarthritis is a degenerative joint disease that can cause pain and stiffness. Treatment may include pain management and physical therapy.",
    "Gout is a form of arthritis characterized by sudden, severe attacks of pain, swelling, and redness in the joints. Medication and dietary changes can help manage gout.",
    "Anemia is a condition characterized by a decrease in the number of red blood cells or a decrease in the amount of hemoglobin in the blood. Treatment depends on the underlying cause and may include iron supplementation or other therapies.",
    "Leukemia is a type of cancer that affects the blood and bone marrow. Treatment depends on the specific type and stage of leukemia and may involve chemotherapy, radiation, and bone marrow transplantation.",
    "Lymphoma is a cancer of the lymphatic system. Treatment includes chemotherapy, radiation therapy, and sometimes stem cell transplantation.",
    "Pancreatitis is inflammation of the pancreas. Treatment may involve hospitalization and supportive care, including fasting and pain management.",
    "Gastritis is inflammation of the stomach lining. Treatment may include medication and dietary changes.",
    "GERD (Gastroesophageal Reflux Disease) is a chronic condition in which stomach acid flows back into the esophagus, leading to symptoms like heartburn. Treatment includes lifestyle changes and medications.",
    "Peptic ulcer is a sore that develops on the lining of the stomach, small intestine, or esophagus. Treatment may involve antibiotics and medication to reduce stomach acid production.",
    "Autism is a complex neurodevelopmental disorder. Early intervention and therapy can help individuals with autism develop skills and manage symptoms.",
    "ADHD (Attention-Deficit/Hyperactivity Disorder) is a neurodevelopmental disorder that affects attention, impulse control, and hyperactivity. Treatment often includes behavior therapy and medication.",
    "Schizophrenia is a mental disorder that affects a person's thoughts, feelings, and behavior. Treatment typically involves antipsychotic medication and psychotherapy.",
    "Bipolar disorder is a mood disorder characterized by cycles of manic and depressive episodes. Treatment may include mood stabilizers, antipsychotic medication, and therapy.",
    "OCD (Obsessive-Compulsive Disorder) is an anxiety disorder characterized by recurring, unwanted thoughts (obsessions) and repetitive behaviors (compulsions). Treatment includes cognitive-behavioral therapy and medication.",
    "PTSD (Post-Traumatic Stress Disorder) can develop after a person has been exposed to a traumatic event. Treatment often involves psychotherapy, medication, or a combination of both.",
    "Anorexia nervosa is an eating disorder characterized by an intense fear of gaining weight and a distorted body image. Treatment includes therapy and nutritional counseling.",
    "Bulimia nervosa is an eating disorder characterized by binge-eating followed by purging behaviors. Treatment includes therapy and sometimes medication.",
    "Binge-eating disorder is an eating disorder characterized by recurring episodes of consuming large amounts of food. Treatment includes therapy and support.",
    "Sickle cell anemia is a genetic blood disorder that causes red blood cells to become misshapen and break down. Treatment aims to manage pain and prevent complications.",
    "Hemophilia is a genetic disorder that impairs the body\'s ability to form blood clots. Treatment involves replacement therapy to replace the missing clotting factor."
]
disease_remedies = [
    "Remedies for hypertension include lifestyle changes like a healthy diet, exercise, and, in some cases, medication.",
    "Managing diabetes involves monitoring your blood sugar levels, taking insulin or oral medications, and making dietary and lifestyle changes.",
    "Preventing heart disease involves a heart-healthy diet, regular exercise, not smoking, and managing other risk factors like high blood pressure and cholesterol.",
    "Cancer treatment options vary and may include surgery, radiation, chemotherapy, immunotherapy, targeted therapy, and precision medicine.",
    "Immediate medical attention is crucial in the case of a stroke. Treatment depends on the type of stroke and may involve medications, surgery, or rehabilitation.",
    "Arthritis management includes physical therapy, pain relief medication, lifestyle modifications, and, in some cases, surgery.",
    "Alzheimer's disease has no cure, but treatment may involve medication to manage symptoms and support for both patients and caregivers.",
    "Asthma can often be managed with medication, including inhalers, and by identifying and avoiding asthma triggers.",
    "COPD treatment includes quitting smoking, medications, oxygen therapy, and pulmonary rehabilitation.",
    "Influenza can be prevented through vaccination, and antiviral medications may be prescribed for severe cases.",
    "Pneumonia treatment involves antibiotics and supportive care, which may include rest, hydration, and fever-reducing medication.",
    "Management of depression may include therapy (such as cognitive-behavioral therapy or medication), lifestyle changes, and support from loved ones.",
    "Anxiety disorders are treated with therapy, medication, or a combination of both, depending on the specific disorder and its severity.",
    "Preventing osteoporosis involves a balanced diet with sufficient calcium and vitamin D, weight-bearing exercise, and, in some cases, medication.",
    "Weight management, diet, exercise, and behavioral changes are key to addressing obesity.",
    "HIV/AIDS management involves antiretroviral therapy (ART) to control the virus's progression and reduce the risk of transmission.",
    "Hepatitis treatment depends on the type of hepatitis and may involve antiviral medications, lifestyle changes, and vaccination.",
    "Malaria prevention includes the use of bed nets, insect repellent, and antimalarial drugs for travelers to endemic areas.",
    "Tuberculosis is treated with a combination of antibiotics over an extended period.",
    "Cholera management focuses on rehydration therapy and sometimes antibiotics.",
    "Vaccination is the most effective way to prevent measles outbreaks.",
    "Chickenpox can be prevented through vaccination, and treatment may include relieving itching and discomfort.",
    "Dengue fever management is supportive, focusing on symptom relief and hydration.",
    "Zika virus prevention involves mosquito bite prevention, especially for pregnant women.",
    "Ebola management includes supportive care, isolation, and contact tracing to prevent the disease's spread.",
    "Chlamydia is treated with antibiotics.",
    "Gonorrhea is treated with antibiotics.",
    "Syphilis is treated with antibiotics.",
    "Herpes outbreaks can be managed with antiviral medications.",
    "Inflammatory bowel disease (IBD) management may involve medication, dietary changes, and sometimes surgery.",
    "Crohn's disease treatment includes medication and, in some cases, surgery to remove affected sections of the digestive tract.",
    "Ulcerative colitis management aims to reduce inflammation and relieve symptoms, sometimes through medication and surgery.",
    "Rheumatoid arthritis treatment includes medication and physical therapy to manage pain and inflammation.",
    "Multiple sclerosis management involves disease-modifying medications, symptom management, and physical therapy.",
    "Parkinson's disease treatment may include medication, physical therapy, and sometimes surgery.",
    "Migraine management includes medication for acute attacks and preventive measures.",
    "Chronic kidney disease management focuses on treating underlying causes, controlling symptoms, and slowing the disease's progression.",
    "Cirrhosis management involves lifestyle changes and treatment for complications.",
    "Irritable bowel syndrome (IBS) management includes dietary modifications, stress management, and medications.",
    "Psoriasis treatment options include topical treatments, phototherapy, and systemic medications.",
    "Eczema management includes emollients, topical steroids, and lifestyle changes to prevent flare-ups.",
    "Lupus treatment may involve medications to control symptoms and lifestyle modifications.",
    "Fibromyalgia management includes medication for pain and other symptoms, as well as lifestyle changes.",
    "PCOS management may include lifestyle changes and medications to regulate menstrual cycles and manage symptoms.",
    "Endometriosis treatment aims to relieve pain and may involve medication and surgery.",
    "Menopause management includes hormone therapy, lifestyle changes, and symptom relief.",
    "Erectile dysfunction treatment options include medication, therapy, and devices.",
    "Premature ejaculation management includes behavioral therapy and, in some cases, medication.",
    "Infertility treatment depends on the underlying causes and may include medication, surgery, or assisted reproductive technologies.",
    "Allergies can be managed by avoiding allergens, using medication, and undergoing allergen-specific immunotherapy.",
    "Celiac disease is primarily managed by adhering to a strict gluten-free diet.",
    "Glaucoma treatment may involve eye drops, laser therapy, or surgery.",
    "Macular degeneration management depends on the type and may include nutritional supplements and medications.",
    "Osteoarthritis management includes pain management, exercise, and lifestyle changes.",
    "Gout treatment includes medication to relieve pain and prevent future attacks.",
    "Anemia treatment is based on the underlying cause and may include iron supplements, vitamin supplements, and other therapies.",
    "Leukemia treatment depends on the specific type and stage and may involve chemotherapy, radiation, and bone marrow transplantation.",
    "Lymphoma treatment includes chemotherapy, radiation therapy, and sometimes stem cell transplantation.",
    "Pancreatitis management involves fasting, pain relief, and addressing underlying causes.",
    "Gastritis treatment may include medication and dietary changes.",
    "GERD management focuses on lifestyle changes, medication, and, in some cases, surgery.",
    "Peptic ulcer treatment may involve antibiotics and medication to reduce stomach acid production.",
    "Autism management includes early intervention, behavioral therapy, and educational support.",
    "ADHD management often includes behavior therapy and medication.",
    "Schizophrenia treatment involves antipsychotic medication and psychotherapy.",
    "Bipolar disorder management may include mood stabilizers, antipsychotic medication, and therapy.",
    "OCD treatment includes cognitive-behavioral therapy and medication.",
    "PTSD management often involves psychotherapy, medication, or a combination of both.",
    "Anorexia nervosa treatment includes therapy and nutritional counseling.",
    "Bulimia nervosa treatment includes therapy and, in some cases, medication.",
    "Binge-eating disorder management includes therapy and support.",
    "Sickle cell anemia treatment aims to manage pain and prevent complications.",
    "Hemophilia treatment involves replacement therapy to replace the missing clotting factor."
]

final_data = []

# Ensure that all lists are of the same length

for i in range(len(diseases)):
    final_data.append((diseases[i], symptoms_list[i], disease_information[i], disease_remedies[i]))

# Output the final data in a format suitable for MySQL insertion
for data in final_data:
    print(data)

symptom_disease_mapping = {
    "Hypertension": "High blood pressure, headaches, dizziness",
    "Diabetes": "Increased thirst, frequent urination, fatigue",
    "Heart disease": "Chest pain, shortness of breath, fatigue",
    "Cancer": "Varies by type and stage, e.g., lumps, weight loss",
    "Stroke": "Numbness, confusion, severe headache, trouble walking",
    "Arthritis": "Joint pain, stiffness, swelling",
    "Alzheimer's disease": "Memory loss, disorientation, behavior changes",
    "Asthma": "Wheezing, shortness of breath, coughing",
    "COPD": "Chronic cough, shortness of breath, wheezing",
    "Influenza": "Fever, cough, sore throat, fatigue",
    "Pneumonia": "High fever, cough with mucus, shortness of breath",
    "Depression": "Persistent sadness, loss of interest, fatigue",
    "Anxiety disorders": "Excessive worry, restlessness, rapid heartbeat",
    "Osteoporosis": "Bone pain, loss of height, fractures",
    "Obesity": "Excessive body weight, increased risk of related conditions",
    "HIV/AIDS": "Fever, fatigue, swollen lymph nodes, opportunistic infections",
    "Hepatitis": "Jaundice, fatigue, abdominal pain, dark urine",
    "Malaria": "High fever with chills, headache, sweating",
    "Tuberculosis": "Cough (often with blood), fever, night sweats",
    "Cholera": "Profuse, watery diarrhea, vomiting, dehydration",
    "Measles": "High fever, cough, red, watery eyes, red rash",
    "Chickenpox": "Itchy rash, fever, fatigue, headache",
    "Dengue fever": "High fever, severe headache, joint and muscle pain",
    "Zika virus": "Mild fever, rash, joint pain, red eyes",
    "Ebola": "Fever, severe headache, muscle pain, vomiting, diarrhea",
    "Chlamydia": "Painful urination, unusual discharge, lower abdominal pain",
    "Gonorrhea": "Painful urination, unusual discharge, pelvic pain",
    "Syphilis": "Sores, rash, fever, fatigue",
    "Herpes": "Painful sores or blisters, itching and tingling",
    "Inflammatory bowel disease (IBD)": "Abdominal pain, diarrhea, weight loss",
    "Crohn's disease": "Diarrhea, abdominal pain, fatigue",
    "Ulcerative colitis": "Bloody diarrhea, abdominal pain, urgency to have a bowel movement",
    "Rheumatoid arthritis": "Joint pain, swelling, morning stiffness, fatigue",
    "Multiple sclerosis": "Fatigue, muscle weakness, numbness, coordination problems",
    "Parkinson's disease": "Tremors, muscle rigidity, slowness of movement",
    "Migraine": "Severe headaches, nausea, sensitivity to light and sound",
    "Chronic kidney disease": "Fatigue, swelling in legs/feet, changes in urination",
    "Cirrhosis": "Fatigue, jaundice, abdominal pain, confusion",
    "Irritable bowel syndrome (IBS)": "Abdominal pain, changes in bowel habits, bloating",
    "Psoriasis": "Red, scaly patches, itching, burning",
    "Eczema": "Dry, itchy skin, rash, inflammation",
    "Lupus": "Fatigue, joint pain, skin rashes, fever",
    "Fibromyalgia": "Widespread pain and tenderness, fatigue, sleep disturbances",
    "PCOS (Polycystic ovary syndrome)": "Irregular periods, excess hair growth, acne, weight gain",
    "Endometriosis": "Pelvic pain, painful periods, painful intercourse",
    "Menopause": "Hot flashes, night sweats, mood swings, vaginal dryness",
    "Erectile dysfunction": "Difficulty achieving/maintaining an erection",
    "Premature ejaculation": "Ejaculation occurring too quickly during sexual intercourse",
    "Infertility": "Difficulty conceiving after a year of trying",
    "Allergies": "Sneezing, runny/stuffy nose, itchy/watery eyes, skin rash",
    "Celiac disease": "Digestive problems, diarrhea, fatigue, skin rash",
    "Glaucoma": "Increased intraocular pressure, gradual loss of peripheral vision",
    "Macular degeneration": "Blurred/distorted central vision",
    "Osteoarthritis": "Joint pain, stiffness, reduced range of motion",
    "Gout": "Sudden, severe joint pain, swelling, redness",
    "Anemia": "Fatigue, weakness, pale skin, shortness of breath",
    "Leukemia": "Fatigue, frequent infections, easy bleeding/bruising, enlarged lymph nodes",
    "Lymphoma": "Swollen lymph nodes, fever, unexplained weight loss",
    "Pancreatitis": "Severe abdominal pain, nausea, vomiting",
    "Gastritis": "Stomach pain/discomfort, nausea, vomiting, bloating",
    "GERD (Gastroesophageal Reflux Disease)": "Heartburn, regurgitation of stomach acid, chest pain",
    "Peptic ulcer": "Burning or gnawing pain in the stomach, nausea, vomiting",
    "Autism": "Difficulty with social interaction, repetitive behaviors, communication challenges",
    "ADHD (Attention-Deficit/Hyperactivity Disorder)": "Inattention, hyperactivity, impulsivity",
    "Schizophrenia": "Delusions, hallucinations, disorganized thinking, social withdrawal",
    "Bipolar disorder": "Episodes of mania and depression, mood swings",
    "OCD (Obsessive-Compulsive Disorder)": "Obsessions, compulsions (repetitive behaviors)",
    "PTSD (Post-Traumatic Stress Disorder)": "Flashbacks, nightmares, anxiety, avoidance behaviors",
    "Anorexia nervosa": "Extreme weight loss, fear of gaining weight, distorted body image",
    "Bulimia nervosa": "Binge eating, followed by purging behaviors (vomiting, laxative use), guilt and shame",
    "Binge-eating disorder": "Recurrent episodes of overeating, feelings of guilt and loss of control",
    "Sickle cell anemia": "Fatigue, pain crises, jaundice, swelling of hands/feet",
    "Hemophilia": "Excessive bleeding, easy bruising, joint pain/swelling"
}

import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Atharv.964",  # Replace with your MySQL password
    database="app"    # Replace with your database name
)

cursor = connection.cursor()


for disease_name, symptoms in symptom_disease_mapping.items():
    update_query = "UPDATE disease_info SET symptoms = %s WHERE disease_name = %s"
    data = (symptoms, disease_name)
    cursor.execute(update_query, data)
    

connection.commit()
cursor.close()

